server:
    port: 10086

system:
    appId: module-pooul
    token: bWlubGlhCg==

# SPRING PROFILES
spring:
    profile: dev
    application:
        name: Module Pooul
    session:
        store-type: redis

    datasource:
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/xmj_contract_dev?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
        name:
        username: root
        password:
#        使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        continue-on-error: true
        initialize: true

    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            max-active: 300
            max-wait: 10000
            max-idle: 50
            min-idle: 10
        timeout: 180

system.security.jwt:
    tokenExpirationTime: 10080 # Number of minutes
    refreshTokenExpTime: 10080 # Minutes
    tokenIssuer: http://minlia.com
    tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus

swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 1.0
    contact: cloud@minlia.com
    path: /api/.*
    redirect: true

mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath*:mybatis/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

# 分页配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

#普尔支付配置-将xxxxxx设置为自己的参数
#pooul:
#    auth:
#        username: xxxxxx
#        password: xxxxxx
#    pay:
#        merchant-id: xxxxxx
#        public-key: xxxxxx
#        private-key: xxxxxx
#        pooul-public-key: xxxxxx
#        pay-url: https://api-dev.pooul.com/v2/pay?merchant_id=${pooul.merchant-id}
#        query-order-url: https://api-dev.pooul.com/v2/pay/query?merchant_id=${pooul.merchant-id}
#        close-order-url: https://api-dev.pooul.com/v2/pay/close?merchant_id=${pooul.merchant-id}
#        notify-url: http://xmj.frp.apartscloud.com/api/open/pooul/notify/pay
#    merchant:
#        platform-merchant-id: xxxxxx
#        parent-id: xxxxxx
#        create-url: https://api-dev.pooul.com/cms/merchants
#        delete-url: https://api-dev.pooul.com/cms/merchants/{merchantId}

#入驻商户-花果山
pooul:
    host: https://api-dev.pooul.com
    auth:
        username: yunguanjia@aliyun.com
        password: xiaoq123
    pay:
        merchant-id: 2162288807443437
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoRlcWxsXeLlqsasMEDfvNZ5OYBdiGZt5D3l7Li17AIi8o0JdRThqwpwF7Oabu+bfwfsMHWGy1fxvIpDLh1ftXkKqoGlQU10WibXTUrH90wYGBJRa4yF8qwdMYkkNi39kWtSbeberUWo1msKF2Oih1JanwXNXGb6DNoOixC2DR1C5wYSkvKqCimsbLNbF5/AOJ3X7EdinSI6PxLmMSGgQAlOJbwhG/fDkw9MYw4Binucy2gyEfoMTYHz6LZmNm06R6x+sETuDNv/ONa7ULA4Ww56YwvlXZJsI65exykY6c7O7UhMWSGjUk9Upk0K3Vg7IVdvuwExcIiEpiv2WZLqcnwIDAQAB
        private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChGVxbGxd4uWqxqwwQN+81nk5gF2IZm3kPeXsuLXsAiLyjQl1FOGrCnAXs5pu75t/B+wwdYbLV/G8ikMuHV+1eQqqgaVBTXRaJtdNSsf3TBgYElFrjIXyrB0xiSQ2Lf2Ra1Jt5t6tRajWawoXY6KHUlqfBc1cZvoM2g6LELYNHULnBhKS8qoKKaxss1sXn8A4ndfsR2KdIjo/EuYxIaBACU4lvCEb98OTD0xjDgGKe5zLaDIR+gxNgfPotmY2bTpHrH6wRO4M2/841rtQsDhbDnpjC+Vdkmwjrl7HKRjpzs7tSExZIaNST1SmTQrdWDshV2+7ATFwiISmK/ZZkupyfAgMBAAECggEAYMRhC4CcerG1ev8pgdx3XZe3sFSbYpJXB4qLCVPcXJfF57MHX3rh9f/ON1zWEuo9YcGwpz12NL8q6nJbLvML6+DTqQNZcpmp3hJP2456zvUBTGLorSICRqFdqnQDJNXirASlV1mSGJdZl5pc18v02UOdhMAJg7dCDc7ISFqmToEhWwmvKpCi7BYK0eb7TlXscfb3mv8g086bTrvYKtYqV7WZG4kxiZ34I0BUslur71NQ5HFjrB1AocdYOOLtz0WHXboQmlT+RRDv/uoFlzcvCcR7HbR46tPQ78YNV+djD+shhTM836ya5r6VnxTM88tFdkxnPTMOkE0U1Xr4Y2APkQKBgQDxOgprB49kphD3Mj34wtUgMs5cQEovJ0b38RZxOsSSmTkw4jIQbXmOvw3Tjo4T4RMelyKszuQHkRbeCgRWmPmaOdfQPm9oDjT/B02CQd1LpJp+c3l7ZUIyx5lV5TkHbWK6LH9E5CmDvRNU3W5/iU/wsP+KPtxHAm8Ay5D1AMAPHQKBgQCq9xORCsdY9hK+cLT9pjjj/mMeq1OhbnLlc6GapvPzhSuqLq7tdumLaffnUu+xAm1/jPf3aUcr97fT2W1mBmg5usQQtC72P1zwgP6+PCZ6WMeKWCNhsTOJUOJmx/pi2lC8KPeTGWZ8jomQXXm4kd19W60a8ge1sFpE7azrsUIh6wKBgQCgiW7rgdGFOxupV290wT0TO5yoOkTkkrAhS/oSivjNU1mDVdXZpvGx9SYfeAzH4A9YWV7DQMDy5DUiuenfM9lRMVOWDCcaSfItE1Aa8vhyYe5LX1AmteHTZ5B9YJqOfdapbfmZAHs8aDWYUfE6wUhJN5IpD+KLA2yaS9+BnekzZQKBgGndkYoxCHw39CdlF04yDexwa+Rj5ueBwzf+QEXJuCpFfmJlggCdr8Sam93sZ2xOuotPOYVE9cNuI7DVZH7W3NdSpXJKgQIO/ngXCKe4C4ObUgSCy3YFCoqvQWKv1oY79d5t59B43BOpF9oDaAo4mNS1Xh3fXZLOXzdrjbZtDyx9AoGACNLSAE+rsiHPfvwOXLRf+AuHDXXVjC9TuOcW13O2sPS+enKw0Y/QaCu9Aj+q3Ctqdt6Jt2snLLmH5yN+VvCxNoW1ZAXYWgfPbqg8jo4c//lOsLz5ibbp6HcH84KtEXulTZ1FuvirUxc69NuZYkqgByC0mYVeu9MqTCR1OMSlcUA=
        pooul-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+Vd3j0McNfR3VvT7mZp/7M6ULFJSc3dh3/56JP8DZk+cDlXC2LR0z0OELJeyTitFeBjpPWzWH3OOFI/OL3nD5/oNZfK+wHd4Tzxj2SdWlyuqRhNv3xG2obUUYZ9urUvkCvxL1SclaXW7cq22V/TTNSgJq7CGdc+q/XLNqcmLt7QIDAQAB
        pay-url: https://api-dev.pooul.com/v2/pay?merchant_id=${pooul.merchant-id}
        query-order-url: https://api-dev.pooul.com/v2/pay/query?merchant_id=${pooul.merchant-id}
        close-order-url: https://api-dev.pooul.com/v2/pay/close?merchant_id=${pooul.merchant-id}
        notify-url: http://xmj.frp.apartscloud.com/api/open/pooul/notify/pay
    merchant:
        platform-merchant-id: 2849928048545130
        parent-id: 2849928048545130
        create-url: https://api-dev.pooul.com/cms/merchants
        delete-url: https://api-dev.pooul.com/cms/merchants/{merchantId}