server:
    port: 30003

system:
    appId: walletapp
    token: bWlubGlhCg==

spring:
    profile: dev
    application:
        name: walletapp
swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 2.0
    contact: cloud@minlia.com
    path: /api/.*


aliyun:
    market:
        bankcard-verify-lianzhuo: 6889a6bedf53468ea27d10f12a8e5159